a= input("Enter Your Name : ")
print("Your Name is", a)
x=input("Enter Your First Number : ")
print(" Your First Number is", x)
y= input("Enter Your Second Number : ")
print("Your First Number is", y)
b=(int(x)+ int(y))
print("Your Solution", b)
c=(int(x)- int(y))
print("Your Solution", c)
d=(int(x)* int(y))
print("Your Solution", d)
e=(int(x)/ int(y))
print("Your Solution", e)
f=(int(x)% int(y))
print("Your Solution", f)